### ISSUE TITLE
inference error

### ISSUE THREAD

**Issue by Alexanderisgod** [Divadi/SOLOFusion#14]
python tools/swap_ema_and_non_ema.py work_dirs/r50-fp16_phase2/r50-fp16-cbgs_phase2_ema.pth 
Traceback (most recent call last):
  File "tools/swap_ema_and_non_ema.py", line 34, in <module>
    main()
  File "tools/swap_ema_and_non_ema.py", line 31, in main
    print(swap_ema_and_non_ema(sys.argv[1]))
  File "tools/swap_ema_and_non_ema.py", line 16, in swap_ema_and_non_ema
    ckpt['state_dict'][k] = ckpt['state_dict'][ema_name]
KeyError: 'ema_pts_bbox_head_shared_conv_conv_weight'

**Comment by xiangyuYIN-Gerald** [comment]
I have also encountered this error, any way to solve it?

**Comment by Divadi** [comment]
I'm not sure how `work_dirs/r50-fp16_phase2/r50-fp16-cbgs_phase2_ema.pth` was generated. Please double check that the EMA flag was enabled during training and/or check that the pth file itself has ema parameters.
