### ISSUE TITLE
Performance mismatch

### ISSUE THREAD

**Issue by thom966** [Divadi/SOLOFusion#15]
Dear author, 

I have executed the training command provided in the readme file to train the R50-SOLOFusion model. However, upon inference, I observed that the model's output exhibited relatively large values for mASE and mAOE compared to the provided weights. 

![image](https://github.com/Divadi/SOLOFusion/assets/84850569/3e2c592a-bf51-4b62-b64e-9c56775e3718)

I did not make any modifications to the code, except for changing the batch size from 16 to 8. I seek guidance on how to reproduce the expected results under these circumstances.

Thank you for your time.

**Comment by smith34567** [comment]
Hey @thom966 
Unfortunately, I have the same problem (similar high values for mASE and mAOE). 
Have you solved it in the meantime and could you help me?
