### ISSUE TITLE
Enlarge perception range

### ISSUE THREAD

**Issue by xhjiang-pixel** [Divadi/SOLOFusion#18]
Dear author,

Hello,
I would like to know which variables should be changed if I want to train solofusion in 150x150m perception range.
I have changed the following:
 point_cloud_range = [-153.6, -153.6, -5.0, 153.6, 153.6, 5.0]; 
grid_config={
     'xbound': [-153.6, 153.6, 0.8],
     'ybound': [-153.6, 153.6, 0.8],
     'zbound': [-5.0, 5.0, 10.0],
     'dbound': [2.0, 158.0, 0.5],}
grid_size=[3072, 3072, 50],
If there is any other variable I missed? Thank you for your time.

**Comment by Divadi** [comment]
I apologize for the delayed response. For future reference, please also double check train_cfg and test_cfg, and bbox_coder.
