### ISSUE TITLE
SOLOFusion Test Model + Config

### ISSUE THREAD

**Issue by abhi1kumar** [Divadi/SOLOFusion#21]
Hi authors,
Thank you for your great work and releasing the Val models. I wanted to build on top of SOLOFusion. However, the [model zoo](https://github.com/Divadi/SOLOFusion#model-zoo) does not contain the nuScenes test model with AP=54.0 and NDS=61.9 as reported in Table 3 of the [paper](https://github.com/Divadi/SOLOFusion#model-zoo).

It would be great if you could release the test model and configs.

**Comment by Divadi** [comment]
I currently do not have access to the checkpoint. The config is just replacing the backbone with ConvNeXt and increasing the grid size.

**Comment by Yzichen** [comment]
@Divadi Are the test results of your also trained on Train+Val set?  Or just Train set.
