### ISSUE TITLE
autoscale_lr only works in non-distributed training

### ISSUE THREAD

**Issue by LMerCy** [Divadi/SOLOFusion#8]
autoscale_lr only works in non-distributed training，because args.gpus and args.gpu_ids are all none in distributed training. But i found your training log, lr is 2e-4, which is scaled by number of gpus, is there anything wrong?

**Comment by Divadi** [comment]
I am not sure if I understood your query; autoscale-lr requires --gpus to be specified in the training command, and it sets gpu_ids here:
https://github.com/Divadi/SOLOFusion/blob/683edce81b619098d1ba143d7b15b1e6aa23337a/tools/train.py#L117-L122
which should then scale the learning rate:
https://github.com/Divadi/SOLOFusion/blob/683edce81b619098d1ba143d7b15b1e6aa23337a/tools/train.py#L124-L126

Please let me know if this did not resolve the question

**Comment by LMerCy** [comment]
> I am not sure if I understood your query; autoscale-lr requires --gpus to be specified in the training command, and it sets gpu_ids here:
> 
> https://github.com/Divadi/SOLOFusion/blob/683edce81b619098d1ba143d7b15b1e6aa23337a/tools/train.py#L117-L122
> 
> 
> which should then scale the learning rate:
> https://github.com/Divadi/SOLOFusion/blob/683edce81b619098d1ba143d7b15b1e6aa23337a/tools/train.py#L124-L126
> 
> Please let me know if this did not resolve the question

when you use distribute training, args. gpu_ids and args.gpus will be None, so the final len(cfg.gpu_ids) is fixed 1.

lr can be scaled right when 'autoscale_lr'  is moved after: 
https://github.com/Divadi/SOLOFusion/blob/main/tools/train.py#L129-L136

**Comment by Divadi** [comment]
"when you use distribute training, args. gpu_ids and args.gpus will be None"
args.gpus should be specified; the default training command is:
```
./tools/dist_train.sh configs/solofusion/r50-fp16_phase1.py 4 --gpus 4 --autoscale-lr --no-validate
```
which includes `--gpus 4` for autoscale-lr
