### ISSUE TITLE
Question about BEVDet and BEVDepth

### ISSUE THREAD

**Issue by jeho-lee** [Divadi/SOLOFusion#9]
Thanks for the great work 👍
As you mentioned in https://github.com/Divadi/SOLOFusion/issues/6#issue-1636804787, the implementations of BEVDepth btw. BEVDepth's official codebase and BEVDet's reproduction are slightly different. And as you know, the reproduction in BEVDet shows lower accuracy.

After comparing the two codebases, I notice that the DepthNet and LSS are identical from the two implementations, 
but **_not for the detection head_** (BEVDet's reproduction uses CenterPoint, not BEVDepthHead).

I think the main reason is the difference in the detection head. 
Furthermore, the mAVE of BEVDet's reproduction that I evaluated is way worse than the official BEVDepth, and as far as I know, the mAVE metric is related to the detection head.

ANY opinions on my assumption? I wonder about your thoughts.

**Comment by jeho-lee** [comment]
After more investigations, I should discard my assumption. 
It seems the detection heads of two implementations are quite similar.

But still I'm curious why two implementations show different eval results.
Could you please give me the detailed code locations or files where the two implementations are different that you mentioned in https://github.com/Divadi/SOLOFusion/issues/6#issue-1636804787?

**Comment by Divadi** [comment]
I remember there being a couple architectural differences between these various view transformation models (BEVDet, LSS, BEVFusion, BEVDepth), as well as some loss/training differences. I didn't mark down all the differences, but I do remember depth loss between BEVDet and BEVDepth being different. Maybe you can reference BEVDet's implementation:
https://github.com/HuangJunJie2017/BEVDet/blob/2919b997c8fb2cb4737fd844200936ef04900d37/mmdet3d/models/detectors/bevdet.py#L362-L381
vs BEVDepth's:
https://github.com/Megvii-BaseDetection/BEVDepth/blob/d78c7b58b10b9ada940462ba83ab24d99cae5833/bevdepth/exps/nuscenes/base_exp.py#L265-L278
I tried to follow BEVDepth's version in this repository:
https://github.com/Divadi/SOLOFusion/blob/683edce81b619098d1ba143d7b15b1e6aa23337a/mmdet3d/models/detectors/solofusion.py#L164-L192

**Comment by jeho-lee** [comment]
Thank you for the detailed answers :)
I will try the depth loss implementation that you provided.
